/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica1_lf.FrontEnd;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brandon
 */
public class FrameReportes extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private Pixel[][] imagen;

    /**
     * Creates new form FrameReportes
     */
    public FrameReportes(Pixel[][] imagen) {
        initComponents();
        this.imagen = imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportesTokens = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaReportesTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Lexema", "Linea", "Columna", "Color"
            }
        ));
        jScrollPane1.setViewportView(tablaReportesTokens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDatosEnTabla() {
        Object[] datosTabla = new Object[5];
        modelo = (DefaultTableModel) tablaReportesTokens.getModel();
        for (int i = 0; i < imagen.length; i++) {
            for (int j = 0; j < imagen[i].length; j++) {
                if (imagen[i][j].getToken() != null) {
                    datosTabla[0] = imagen[i][j].getToken().getTipo().toString();
                    datosTabla[1] = imagen[i][j].getToken().getLexema().toString();
                    datosTabla[2] = imagen[i][j].getToken().getFila()+1;
                    datosTabla[3] = imagen[i][j].getToken().getColumna()+1;
                    datosTabla[4] = imagen[i][j].getToken().getColor();
                    modelo.addRow(datosTabla);
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportesTokens;
    // End of variables declaration//GEN-END:variables
}
