/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.practica1_lf.FrontEnd;

import com.mycompany.practica1_lf.BackEnd.Controlador;
import com.mycompany.practica1_lf.Exceptions.ExceptionsAnalizadorLexico;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author brandon
 */
public class SolicitarFilasColumnas extends javax.swing.JDialog {

    private FrameAnalizadorLexico frameAnalizadorLexico;
    private Controlador controlador;
    /**
     * Creates new form SolicitarFilasColumnas
     */
    public SolicitarFilasColumnas(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.frameAnalizadorLexico = (FrameAnalizadorLexico) (JFrame) parent;
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaTextoColumnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cajaTextoFilas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrarDimensiones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingrese el numero de columnas");

        jLabel2.setText("Ingrese el numero de filas");

        botonRegistrarDimensiones.setText("Guardar Dimensiones");
        botonRegistrarDimensiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarDimensionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaTextoColumnas, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(cajaTextoFilas))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(botonRegistrarDimensiones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaTextoColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaTextoFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(botonRegistrarDimensiones)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarDimensionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarDimensionesActionPerformed
        // TODO add your handling code here:
        try {
            validarDimensiones();
            
            this.setVisible(false);
        } catch (ExceptionsAnalizadorLexico e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarDimensionesActionPerformed

    private void validarDimensiones()throws ExceptionsAnalizadorLexico{
        if (!validarDatos(cajaTextoColumnas.getText())) {
            throw new ExceptionsAnalizadorLexico("Ingrese solo numeros");
        }
        if (cajaTextoColumnas == null || cajaTextoColumnas.getText().isBlank()) {
            throw new ExceptionsAnalizadorLexico("Verifique que todos los campos esten cubiertos");
        }
        if (!validarDatos(cajaTextoFilas.getText())) {
            throw new ExceptionsAnalizadorLexico("Ingrese solo numeros");
        }
        if (cajaTextoFilas == null || cajaTextoFilas.getText().isBlank()) {
            throw new ExceptionsAnalizadorLexico("Verfique que todos los campos esten ingresados");
        }
        frameAnalizadorLexico.setTamañoColumnas(Integer.valueOf(cajaTextoColumnas.getText()));
        frameAnalizadorLexico.setTamañoFilas(Integer.valueOf(cajaTextoFilas.getText()));
    }
    
    private boolean validarDatos(String dato){
        return dato.matches("[0-9]*");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarDimensiones;
    private javax.swing.JTextField cajaTextoColumnas;
    private javax.swing.JTextField cajaTextoFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
